### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by alim4** [DannyMoerkerke/brackets-selections#2]
Using the Ctrl+Shift commands don't work

**Comment by DannyMoerkerke** [comment]
Thanks for reporting and sorry for the very late reply!
Which version are you running and which platform?

**Comment by epstarr** [comment]
Interested in using a plugin like this, however it doesn't work for me either.

Release 1.3 build 1.3.0-16022 on Windows 7 Enterprise

**Comment by DannyMoerkerke** [comment]
What exact issue are you having? Doesn't it work at all? Any console output?

**Comment by dippe** [comment]
Hi! The same issue.

My brackets extension manager installed version doesn't contains the windows and linux keybindings which are in the github version (can check: Help -> Show extensions folder -> installed plugin source).

**Comment by DannyMoerkerke** [comment]
I added the version with the keybindings (1.0.1) for Windows and Linux to the Brackets Extensions Registry.
