### ISSUE TITLE
Select to start / end is built in in Brackets

### ISSUE THREAD

**Issue by PhiLhoSoft** [DannyMoerkerke/brackets-selections#3]
Not sure if the comment is just outdated by newer versions of Brackets, but the remark "_It also enables you to select everything from the current position to the start or the end of the document which, stangely enough, is not possible in Brackets out of the box._" is not true for the current (1.3) version of Brackets.
I just tried Ctrl+Shift+Home and Ctrl+Shift+End (classical shortcuts for these commands) and it just worked.
You might want to update this part of the readme.

**Comment by DannyMoerkerke** [comment]
Thanks! I updated the readme.
